### ISSUE TITLE
lack of examples

### ISSUE THREAD

**Issue by mortezamsp** [berenger-eu/tbfmm#12]
There are 5 examples which works with different kernels. However, I am looking for an example that changes Algorithm to TbfOpenmpAlgorithm or TbfSmSpecxAlgorithm classes. When I modify the example "testRandomParticlesTsm.cpp" to set the algorithm to openmp one, I get this error:

`using AlgorithmClass = TbfOpenmpAlgorithm<RealType, TbfTestKernel<RealType>>`
returns compile error:
`/home/msp/Downloads/tbfmm-master/src/algorithms/openmp/tbfopenmpalgorithm.hpp:231:45: error: ‘class TbfTreeTsm<double, double, 3, long int, 1, std::array<long int, 1>, std::array<long int, 1> >’ has no member named ‘getLeafGroups’; did you mean ‘getLeafGroupsSource’?`

would you please add example for parallel algorithms too? because in your paper you used a parallel infrastructure and I want to test it.

**Comment by berenger-eu** [comment]
Hello, if you look at the original code `TbfAlgorithmSelecter::type`, if we look at it points to, you will see:
```cpp
struct TbfAlgorithmSelecterTsm{
    template<typename RealType, class KernelClass, class SpaceIndexType = TbfDefaultSpaceIndexType<RealType>>
#ifdef TBF_USE_STARPU
    using type = TbfSmStarpuAlgorithmTsm<RealType, KernelClass, SpaceIndexType>;
#elif defined(TBF_USE_SPECX)
    using type = TbfSmSpecxAlgorithmTsm<RealType, KernelClass, SpaceIndexType>;
#elif defined(TBF_USE_OPENMP)
    using type = TbfOpenmpAlgorithmTsm<RealType, KernelClass, SpaceIndexType>;
#else
    using type = TbfAlgorithmTsm<RealType, KernelClass, SpaceIndexType>;
#endif
};
```
Therefore, you can select one of them, like `TbfOpenmpAlgorithmTsm` (but not `TbfOpenmpAlgorithm`).

**Comment by berenger-eu** [comment]
As a side remark, the `starpu` is expected to go faster (especially, there is now a CUDA version with StarPU, but for the classic algo, not the target source model, i.e., when targets and sources are different).
